import "./globals.css";
import ClientProvider from "./ClientProvider";
import { cookies } from "next/headers";
import { verify } from "jsonwebtoken";
import { Toaster } from "react-hot-toast";
import { Vazirmatn } from "next/font/google";
import BottomNav from "@/Components/bottomNav/BottomNav";
import Footer from "@/Components/footer/Footer";
import Navbar from "@/Components/navbar/Navbar";

const vazirmatn = Vazirmatn({
  subsets: ['arabic'],
  weight: ['400', '700'],
  display: 'swap',
});

export const metadata = {
  title: "Uni Club",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let userData = null
  const tokenCookie = (await cookies()).get('token')
  const token = tokenCookie?.value
  try {
    userData = verify(token, process.env.ACCESSTOKEN_SECRETKEY)
  } catch {
    userData = null
  }
  return (
    <html lang="fa">
      <body
        dir="rtl"
        className={`${vazirmatn.className} antialiased bg-zinc-900`}
      >
        <ClientProvider userData={userData}>
          <Navbar />
          {children}
          <BottomNav />
          <Toaster />
        </ClientProvider>
        <Footer/>
      </body>
    </html>
  );
}
